import { useState, useEffect } from 'react';
import { useConfirm } from '../hooks/useConfirm.js';
import { EFFORT_COLORS, getModelLabel, getModelProvider, formatCost, formatTokens } from '../utils.js';

export default function CardModal({ task, project, onClose, onExecute, onPlan, onDismiss, onAbort, onDequeue, onUpdateTask, models }) {
  if (!task) return null;

  const isProposed = task.status === 'proposed';
  const isPlanning = task.status === 'planning';
  const isPlanned = task.status === 'planned';
  const isQueued = task.status === 'queued';
  const isExecuting = task.status === 'executing';
  const isDone = task.status === 'done';
  const isEditable = isProposed || isPlanned;

  // Default model: same as generating model, or first available
  const defaultModelId = task.generatedBy || (models?.[0]?.id) || 'claude-opus-4-6';
  const [selectedModelId, setSelectedModelId] = useState(defaultModelId);
  const [confirmingDismiss, armDismiss, resetDismiss] = useConfirm();

  // Edit mode state
  const [editing, setEditing] = useState(false);
  const [draftTitle, setDraftTitle] = useState('');
  const [draftDescription, setDraftDescription] = useState('');
  const [draftRationale, setDraftRationale] = useState('');
  const [draftEffort, setDraftEffort] = useState('medium');
  const [draftPlan, setDraftPlan] = useState('');

  useEffect(() => { resetDismiss(); setEditing(false); }, [task?.id]);

  const enterEditMode = () => {
    setDraftTitle(task.title || '');
    setDraftDescription(task.description || '');
    setDraftRationale(task.rationale || '');
    setDraftEffort(task.effort || 'medium');
    setDraftPlan(task.plan || '');
    setEditing(true);
  };

  const cancelEdit = () => {
    setEditing(false);
  };

  const saveEdit = () => {
    const updates = {
      title: draftTitle,
      description: draftDescription,
      rationale: draftRationale,
      effort: draftEffort,
    };
    if (isPlanned && task.plan != null) {
      updates.plan = draftPlan;
    }
    onUpdateTask(task.id, updates);
    setEditing(false);
  };

  // Resolve model labels for display
  const generatedByLabel = getModelLabel(task.generatedBy, models);
  const plannedByLabel = getModelLabel(task.plannedBy, models);
  const executedByLabel = getModelLabel(task.executedBy, models);
  const generatedByProvider = getModelProvider(task.generatedBy, models);
  const plannedByProvider = getModelProvider(task.plannedBy, models);
  const executedByProvider = getModelProvider(task.executedBy, models);

  // Backwards compat for old agentType field
  const legacyLabel = !task.generatedBy && !task.executedBy && task.agentType
    ? task.agentType.charAt(0).toUpperCase() + task.agentType.slice(1)
    : null;

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          {editing ? (
            <input
              type="text"
              className="input modal-edit-title"
              value={draftTitle}
              onChange={(e) => setDraftTitle(e.target.value)}
              placeholder="Task title"
            />
          ) : (
            <h2 className="modal-title">{task.title}</h2>
          )}
          <button className="modal-close" onClick={onClose}>&times;</button>
        </div>

        <div className="modal-meta">
          {editing ? (
            <select
              className="select modal-edit-effort"
              value={draftEffort}
              onChange={(e) => setDraftEffort(e.target.value)}
            >
              <option value="small">small</option>
              <option value="medium">medium</option>
              <option value="large">large</option>
            </select>
          ) : (
            <span
              className="effort-badge"
              style={{ backgroundColor: EFFORT_COLORS[task.effort] || EFFORT_COLORS.medium }}
            >
              {task.effort}
            </span>
          )}
          {generatedByLabel && (
            <span className={`model-badge model-${generatedByProvider}`} title="Generated by">
              {generatedByLabel}
            </span>
          )}
          {plannedByLabel && (
            <span className={`model-badge model-${plannedByProvider}`} title="Planned by">
              {plannedByLabel}
            </span>
          )}
          {executedByLabel && (
            <span className={`model-badge model-${executedByProvider}`} title="Executed by">
              {executedByLabel}
            </span>
          )}
          {legacyLabel && (
            <span className={`model-badge model-${task.agentType}`}>
              {legacyLabel}
            </span>
          )}
          {project && (
            <span className="project-badge">
              {project.name}
            </span>
          )}
          <span className="modal-status">{task.status}</span>
          {isDone && task.commitHash && (
            <span className="commit-hash">{task.commitHash.slice(0, 7)}</span>
          )}
          {task.costUsd > 0 && (
            <span className="cost-badge">{formatCost(task.costUsd)}</span>
          )}
        </div>

        <div className="modal-section">
          <h3>Description</h3>
          {editing ? (
            <textarea
              className="input modal-edit-textarea"
              value={draftDescription}
              onChange={(e) => setDraftDescription(e.target.value)}
              rows={4}
              placeholder="Task description"
            />
          ) : (
            <p>{task.description}</p>
          )}
        </div>

        {(editing || task.rationale) && (
          <div className="modal-section">
            <h3>Rationale</h3>
            {editing ? (
              <textarea
                className="input modal-edit-textarea"
                value={draftRationale}
                onChange={(e) => setDraftRationale(e.target.value)}
                rows={3}
                placeholder="Why this task matters"
              />
            ) : (
              <p>{task.rationale}</p>
            )}
          </div>
        )}

        {(editing && isPlanned) || task.plan ? (
          <div className="modal-section">
            <h3>Implementation Plan</h3>
            {editing && isPlanned ? (
              <textarea
                className="input modal-edit-textarea modal-edit-plan"
                value={draftPlan}
                onChange={(e) => setDraftPlan(e.target.value)}
                rows={10}
              />
            ) : (
              <pre className="modal-plan">{task.plan}</pre>
            )}
          </div>
        ) : null}

        {isDone && task.agentLog && (
          <div className="modal-section">
            <h3>Agent Log</h3>
            <pre className="modal-log">{task.agentLog}</pre>
          </div>
        )}

        {task.costUsd > 0 && (
          <div className="modal-section modal-cost-section">
            <h3>Cost</h3>
            <div className="cost-summary">
              <span className="cost-total">{formatCost(task.costUsd)}</span>
              {task.tokenUsage && (
                <div className="cost-breakdown">
                  {task.tokenUsage.generation && (
                    <div className="cost-phase">
                      <span className="cost-phase-label">Generation</span>
                      <span className="cost-phase-tokens">
                        {formatTokens(task.tokenUsage.generation.input)} in / {formatTokens(task.tokenUsage.generation.output)} out
                      </span>
                    </div>
                  )}
                  {task.tokenUsage.planning && (
                    <div className="cost-phase">
                      <span className="cost-phase-label">Planning</span>
                      <span className="cost-phase-tokens">
                        {formatTokens(task.tokenUsage.planning.input)} in / {formatTokens(task.tokenUsage.planning.output)} out
                      </span>
                    </div>
                  )}
                  {task.tokenUsage.execution && (
                    <div className="cost-phase">
                      <span className="cost-phase-label">Execution</span>
                      <span className="cost-phase-tokens">
                        {formatTokens(task.tokenUsage.execution.input)} in / {formatTokens(task.tokenUsage.execution.output)} out
                      </span>
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>
        )}

        {isProposed && (
          <div className="modal-actions">
            {editing ? (
              <>
                <button className="btn btn-save" onClick={saveEdit}>Save</button>
                <button className="btn btn-cancel" onClick={cancelEdit}>Cancel</button>
              </>
            ) : (
              <>
                <button className="btn btn-edit" onClick={enterEditMode}>Edit</button>
                <select
                  className="select model-select"
                  value={selectedModelId}
                  onChange={(e) => setSelectedModelId(e.target.value)}
                >
                  {(models || []).map((m) => (
                    <option key={m.id} value={m.id}>{m.label}</option>
                  ))}
                </select>
                <button className="btn btn-plan" onClick={() => { onPlan(task.id, selectedModelId); onClose(); }}>
                  Plan
                </button>
                <button
                  className={`btn btn-dismiss${confirmingDismiss ? ' confirming' : ''}`}
                  onClick={() => {
                    if (confirmingDismiss) { resetDismiss(); onDismiss(task.id); onClose(); }
                    else { armDismiss(); }
                  }}
                >
                  {confirmingDismiss ? 'Are you sure?' : 'Dismiss'}
                </button>
              </>
            )}
          </div>
        )}

        {isPlanned && (
          <div className="modal-actions">
            {editing ? (
              <>
                <button className="btn btn-save" onClick={saveEdit}>Save</button>
                <button className="btn btn-cancel" onClick={cancelEdit}>Cancel</button>
              </>
            ) : (
              <>
                <button className="btn btn-edit" onClick={enterEditMode}>Edit</button>
                <select
                  className="select model-select"
                  value={selectedModelId}
                  onChange={(e) => setSelectedModelId(e.target.value)}
                >
                  {(models || []).map((m) => (
                    <option key={m.id} value={m.id}>{m.label}</option>
                  ))}
                </select>
                <button className="btn btn-execute" onClick={() => { onExecute(task.id, selectedModelId); onClose(); }}>
                  Execute
                </button>
                <button
                  className={`btn btn-dismiss${confirmingDismiss ? ' confirming' : ''}`}
                  onClick={() => {
                    if (confirmingDismiss) { resetDismiss(); onDismiss(task.id); onClose(); }
                    else { armDismiss(); }
                  }}
                >
                  {confirmingDismiss ? 'Are you sure?' : 'Dismiss'}
                </button>
              </>
            )}
          </div>
        )}

        {isPlanning && (
          <div className="modal-actions">
            <button
              className={`btn btn-dismiss${confirmingDismiss ? ' confirming' : ''}`}
              onClick={() => {
                if (confirmingDismiss) { resetDismiss(); onDismiss(task.id); onClose(); }
                else { armDismiss(); }
              }}
            >
              {confirmingDismiss ? 'Are you sure?' : 'Cancel Planning'}
            </button>
          </div>
        )}

        {isQueued && (
          <div className="modal-actions">
            <span className="modal-status">Queued{task.queuePosition ? ` #${task.queuePosition}` : ''}</span>
            <button className="btn btn-abort" onClick={() => { onDequeue(task.id); onClose(); }}>
              Dequeue
            </button>
            <button
              className={`btn btn-dismiss${confirmingDismiss ? ' confirming' : ''}`}
              onClick={() => {
                if (confirmingDismiss) { resetDismiss(); onDismiss(task.id); onClose(); }
                else { armDismiss(); }
              }}
            >
              {confirmingDismiss ? 'Are you sure?' : 'Dismiss'}
            </button>
          </div>
        )}

        {isExecuting && (
          <div className="modal-actions">
            <button className="btn btn-abort" onClick={() => { onAbort(task.id); onClose(); }}>
              Abort Execution
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
