import { useState } from 'react';

const EFFORT_COLORS = {
  small: '#4ade80',
  medium: '#facc15',
  large: '#f87171',
};

function getModelLabel(modelId, models) {
  if (!modelId) return null;
  if (models?.length) {
    const found = models.find((m) => m.id === modelId);
    if (found) return found.label;
    return modelId;
  }
  return modelId;
}

function getModelProvider(modelId, models) {
  if (!modelId || !models?.length) return 'claude';
  const found = models.find((m) => m.id === modelId);
  return found ? found.provider : 'claude';
}

export default function CardModal({ task, project, onClose, onExecute, onPlan, onDismiss, models }) {
  if (!task) return null;

  const isProposed = task.status === 'proposed';
  const isPlanned = task.status === 'planned';
  const isDone = task.status === 'done';

  // Default model: same as generating model, or first available
  const defaultModelId = task.generatedBy || (models?.[0]?.id) || 'claude-opus-4-6';
  const [selectedModelId, setSelectedModelId] = useState(defaultModelId);

  // Resolve model labels for display
  const generatedByLabel = getModelLabel(task.generatedBy, models);
  const plannedByLabel = getModelLabel(task.plannedBy, models);
  const executedByLabel = getModelLabel(task.executedBy, models);
  const generatedByProvider = getModelProvider(task.generatedBy, models);
  const plannedByProvider = getModelProvider(task.plannedBy, models);
  const executedByProvider = getModelProvider(task.executedBy, models);

  // Backwards compat for old agentType field
  const legacyLabel = !task.generatedBy && !task.executedBy && task.agentType
    ? task.agentType.charAt(0).toUpperCase() + task.agentType.slice(1)
    : null;

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <h2 className="modal-title">{task.title}</h2>
          <button className="modal-close" onClick={onClose}>&times;</button>
        </div>

        <div className="modal-meta">
          <span
            className="effort-badge"
            style={{ backgroundColor: EFFORT_COLORS[task.effort] || EFFORT_COLORS.medium }}
          >
            {task.effort}
          </span>
          {generatedByLabel && (
            <span className={`model-badge model-${generatedByProvider}`} title="Generated by">
              {generatedByLabel}
            </span>
          )}
          {plannedByLabel && (
            <span className={`model-badge model-${plannedByProvider}`} title="Planned by">
              {plannedByLabel}
            </span>
          )}
          {executedByLabel && (
            <span className={`model-badge model-${executedByProvider}`} title="Executed by">
              {executedByLabel}
            </span>
          )}
          {legacyLabel && (
            <span className={`model-badge model-${task.agentType}`}>
              {legacyLabel}
            </span>
          )}
          {project && (
            <span className="project-badge">
              {project.name}
            </span>
          )}
          <span className="modal-status">{task.status}</span>
          {isDone && task.commitHash && (
            <span className="commit-hash">{task.commitHash.slice(0, 7)}</span>
          )}
        </div>

        <div className="modal-section">
          <h3>Description</h3>
          <p>{task.description}</p>
        </div>

        {task.rationale && (
          <div className="modal-section">
            <h3>Rationale</h3>
            <p>{task.rationale}</p>
          </div>
        )}

        {task.plan && (
          <div className="modal-section">
            <h3>Implementation Plan</h3>
            <pre className="modal-plan">{task.plan}</pre>
          </div>
        )}

        {isDone && task.agentLog && (
          <div className="modal-section">
            <h3>Agent Log</h3>
            <pre className="modal-log">{task.agentLog}</pre>
          </div>
        )}

        {isProposed && (
          <div className="modal-actions">
            <select
              className="select model-select"
              value={selectedModelId}
              onChange={(e) => setSelectedModelId(e.target.value)}
            >
              {(models || []).map((m) => (
                <option key={m.id} value={m.id}>{m.label}</option>
              ))}
            </select>
            <button className="btn btn-plan" onClick={() => { onPlan(task.id, selectedModelId); onClose(); }}>
              Plan
            </button>
            <button className="btn btn-dismiss" onClick={() => { onDismiss(task.id); onClose(); }}>
              Dismiss
            </button>
          </div>
        )}

        {isPlanned && (
          <div className="modal-actions">
            <select
              className="select model-select"
              value={selectedModelId}
              onChange={(e) => setSelectedModelId(e.target.value)}
            >
              {(models || []).map((m) => (
                <option key={m.id} value={m.id}>{m.label}</option>
              ))}
            </select>
            <button className="btn btn-execute" onClick={() => { onExecute(task.id, selectedModelId); onClose(); }}>
              Execute
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
